services:
  phpfpm:
    build: .
    volumes:
      - .:/var/www/
    environment:
      - APP_ENV=dev
      - APP_SECRET=your_secret_key
      - DATABASE_URL=mysql://root:password@db:3306/symfony
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - phpfpm

volumes:
  db_data:
